### ISSUE TITLE
Warning : wide color not active

### ISSUE THREAD

**Issue by theRealGupta** [edmonston/wide-color-viewer#1]
Hi,

I download your code and install but I m getting **Warning: wide color not active** what is the solution to this?

**Comment by edmonston** [comment]
Hi there! What device are you running it on? Wide Color is only available on iPhone 7, 7 Plus, 8, 8 Plus or X.

**Comment by theRealGupta** [comment]
Hi,
Thank You for your quick reply I was testing in iPhone SE. Today I test on iPhone 8 its work good. 

Thank You :)
